# Generated by Django 5.2.4 on 2025-07-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField()),
                ('humedad_ambiente', models.FloatField()),
                ('humedad_suelo', models.IntegerField()),
                ('movimiento', models.BooleanField()),
            ],
        ),
    ]
